package com.wsb.findapart.model

data class ListItem (
    val id: String,
    val city: String,
    val type: String,
    val area: String,
    val room: String,
    val floor: String,
    val floorcount: String,
    val buildyear: String,
    val centredistance: String,
    val poicount: String,
    val schooldistance: String,
    val clinicdistance: String,
    val postofficedistance: String,
    val kindergartendistance: String,
    val restaurantdistance: String,
    val collegedistance: String,
    val pharmacydistance: String,
    val ownership: String,
    val buildingmaterial: String,
    val condition: String,
    val hasparkingspace: String,
    val hasbalcony: String,
    val haselevator: String,
    val hassecurity: String,
    val hasstorageroom: String,
    val price: String
)